### ISSUE TITLE
Current release 21.8.1 is not working properly - Golang

### ISSUE THREAD

**Issue by JulianHauber** [whitesource/unified-agent-distribution#18]
I´m using the latest wss-unified-agent.jar, which is currently 21.8.1. However, since 21.8.1 was released Whitesource is not finding dependencies anymore. If I use the tag v21.7.2 instead, the Whitesource scan runs as before and is finding dependencies in the code again.

**Comment by LenaKleyner** [comment]
Hi @JulianHauber , we will need more information to evaluate your issue. Could you please open a support ticket (support@whitesourcesoftware.com) with all the relevant information (the Unified Agent execution command, its settings, and the output log)?

Thanks!

Lena

**Comment by JulianHauber** [comment]
Hi @LenaKleyner. Thank you very much for your quick response.

Here are the output logs of both, UnifiedAgent version 21.7.2 and 21.8.1.

`13:08:16  [INFO] [2021-08-30 11:08:16,303 +0000] - UnifiedAgent version (pluginVersion) : 21.7.2
13:08:16  [INFO] [2021-08-30 11:08:16,324 +0000] - 

...

13:08:17  ------------------------------------------------------------------------
13:08:17  -------------------- Start: Scan Files Matching Includes Pattern -------
13:08:17  ------------------------------------------------------------------------
13:08:17  [INFO] [2021-08-30 11:08:17,191 +0000] - Attempting to resolve dependencies
13:08:17  [INFO] [2021-08-30 11:08:17,191 +0000] - 
13:08:17  ------------------------------------------------------------------------
13:08:17  -------------------- Start: Pre-Step And Resolve Dependencies ----------
13:08:17  ------------------------------------------------------------------------
13:08:17  [INFO] [2021-08-30 11:08:17,263 +0000] - Trying to resolve GO dependencies
13:08:17  [INFO] [2021-08-30 11:08:17,412 +0000] - topFolder = /home/jenkins/agent/workspace/sample_master
13:08:17  [INFO] [2021-08-30 11:08:17,412 +0000] - Resolve dependencies - START - modules
13:08:18  [WARN] [2021-08-30 11:08:18,756 +0000] - Read error line #1: go: downloading github.com/sirupsen/logrus v1.4.2
13:08:18  [WARN] [2021-08-30 11:08:18,756 +0000] - Read error line #2: go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
13:08:19  [WARN] [2021-08-30 11:08:18,962 +0000] - Read error line #1: go: downloading github.com/jstemmer/go-junit-report v0.9.1
13:08:19  [WARN] [2021-08-30 11:08:18,962 +0000] - Read error line #2: go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
13:08:19  [WARN] [2021-08-30 11:08:18,978 +0000] - Read error line #1: go: creating new go.mod: module main
13:08:19  [WARN] [2021-08-30 11:08:18,978 +0000] - Read error line #2: go: to add module requirements and sums:
13:08:19  [WARN] [2021-08-30 11:08:18,994 +0000] - Read error line #3: 	go mod tidy
13:08:19  [INFO] [2021-08-30 11:08:19,671 +0000] - Building Hierarchy Tree for all direct dependencies
13:08:19  [INFO] [2021-08-30 11:08:19,672 +0000] - Building hierarchy tree for github.com/jstemmer/go-junit-report
13:08:19  [INFO] [2021-08-30 11:08:19,673 +0000] - Building hierarchy tree for github.com/sirupsen/logrus
13:08:19  [INFO] [2021-08-30 11:08:19,677 +0000] - Resolve dependencies - END - modules
13:08:19  [INFO] [2021-08-30 11:08:19,680 +0000] - 
13:08:19  ------------------------------------------------------------------------
13:08:19  -------------------- End: Pre-Step And Resolve Dependencies ------------
13:08:19  ------------------------------------------------------------------------
13:08:19  [INFO] [2021-08-30 11:08:19,682 +0000] - Skipping scanning directories for matching source/binary files - controlled by flags: ignoreSourceFiles and fileSystemScan
13:08:19  [INFO] [2021-08-30 11:08:19,682 +0000] - 
13:08:19  ------------------------------------------------------------------------
13:08:19  -------------------- End: Scan Files Matching Includes Pattern ---------
13:08:19  ------------------------------------------------------------------------
13:08:19  [INFO] [2021-08-30 11:08:19,682 +0000] - Finished analyzing Files
13:08:19  [INFO] [2021-08-30 11:08:19,692 +0000] - Initializing WhiteSource Client
13:08:19  [INFO] [2021-08-30 11:08:19,694 +0000] - Service URL is https://saas.whitesourcesoftware.com/agent
13:08:19  [INFO] [2021-08-30 11:08:19,720 +0000] - UpdateType set to OVERRIDE 
13:08:19  [INFO] [2021-08-30 11:08:19,720 +0000] - 
13:08:19  ------------------------------------------------------------------------
13:08:19  -------------------- Start: Check Policies -----------------------------
13:08:19  ------------------------------------------------------------------------
13:08:19  [INFO] [2021-08-30 11:08:19,720 +0000] - Checking policies
13:08:22  [INFO] [2021-08-30 11:08:21,991 +0000] - All dependencies conform with open source policies.
13:08:22  [INFO] [2021-08-30 11:08:21,991 +0000] - Check Policies Support Token: 3438827cb4bcd49cd82ecdfc9c924d13a1630321700453
13:08:22  [INFO] [2021-08-30 11:08:22,214 +0000] - Policies report generated successfully
13:08:22  [INFO] [2021-08-30 11:08:22,214 +0000] - 
13:08:22  ------------------------------------------------------------------------
13:08:22  -------------------- End: Check Policies -------------------------------
13:08:22  ------------------------------------------------------------------------
13:08:22  [INFO] [2021-08-30 11:08:22,215 +0000] - Sending Update
13:08:22  [INFO] [2021-08-30 11:08:22,215 +0000] - 
13:08:22  ------------------------------------------------------------------------
13:08:22  -------------------- Start: Update Inventory ---------------------------
13:08:22  ------------------------------------------------------------------------
13:08:23  [INFO] [2021-08-30 11:08:23,371 +0000] - 
13:08:23  ------------------------------------------------------------------------
13:08:23  -------------------- End: Update Inventory -----------------------------
13:08:23  ------------------------------------------------------------------------
13:08:23  [INFO] [2021-08-30 11:08:23,371 +0000] - Inventory update results for SAP SE
13:08:23  [INFO] [2021-08-30 11:08:23,371 +0000] - No new projects found.
13:08:23  [INFO] [2021-08-30 11:08:23,371 +0000] - Updated projects:
13:08:23  [INFO] [2021-08-30 11:08:23,371 +0000] - # <ProjectName>
13:08:23  [INFO] [2021-08-30 11:08:23,371 +0000] - Project name: <ProjectName>, URL: <project>
13:08:23  [INFO] [2021-08-30 11:08:23,371 +0000] - Support Token: 08ecdbc9f8b234b3680c89f0865bc0d351630321702273
13:08:23  [INFO] [2021-08-30 11:08:23,374 +0000] - Log files are found at: ./whitesource/Mon-Aug-30-2021-11.08.16
13:08:23  [INFO] [2021-08-30 11:08:23,376 +0000] - 
13:08:23  ------------------------------------------------------------------------------------------------------------------------------------------------------
13:08:23  ------------------------------------------------------------- WhiteSource Scan Summary: --------------------------------------------------------------
13:08:23  ------------------------------------------------------------------------------------------------------------------------------------------------------
13:08:23  ======================================================================================================================================================
13:08:23  Scan Origin: Local File System
13:08:23  ======================================================================================================================================================
13:08:23  Step                                              Completion Status               Elapsed                  Comments
13:08:23  ======================================================================================================================================================
13:08:23  Fetch Configuration                                  COMPLETED                  00:00:00.072               --------
13:08:23  Pre-Step And Resolve Dependencies                    COMPLETED                  00:00:02.489               6 total dependencies (6 unique)
13:08:23     GO                                                COMPLETED                  00:00:02.416               6 total dependencies (6 unique)
13:08:23  Scan Files Matching Includes Pattern                 COMPLETED                  00:00:00.152               0 source/binary files
13:08:23  Check Policies                                       COMPLETED                  00:00:02.494               --------
13:08:23  Update Inventory                                     COMPLETED                  00:00:01.156               1 updated projects
13:08:23  
13:08:23  ======================================================================================================================================================
13:08:23  Elapsed running time:                                                           00:00:06.363
13:08:23  ======================================================================================================================================================
13:08:23  Process finished with exit code SUCCESS (0)`

`[2021-08-30T10:24:20.149Z] [INFO] [2021-08-30 10:24:19,967 +0000] - UnifiedAgent version (pluginVersion) : 21.8.1
[2021-08-30T10:24:20.149Z] [INFO] [2021-08-30 10:24:19,990 +0000] - 

...

[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] -------------------- Start: Scan Files Matching Includes Pattern -------
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,842 +0000] - Attempting to resolve dependencies
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,842 +0000] - 
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] -------------------- Start: Pre-Step And Resolve Dependencies ----------
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,860 +0000] - 
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] -------------------- End: Pre-Step And Resolve Dependencies ------------
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,862 +0000] - Skipping scanning directories for matching source/binary files - controlled by flags: ignoreSourceFiles and fileSystemScan
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,862 +0000] - 
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] -------------------- End: Scan Files Matching Includes Pattern ---------
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,862 +0000] - Finished analyzing Files
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,881 +0000] - Initializing WhiteSource Client
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,882 +0000] - Service URL is https://saas.whitesourcesoftware.com/agent
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,908 +0000] - UpdateType set to OVERRIDE 
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,908 +0000] - 
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] -------------------- Start: Check Policies -----------------------------
[2021-08-30T10:24:20.982Z] ------------------------------------------------------------------------
[2021-08-30T10:24:20.982Z] [INFO] [2021-08-30 10:24:20,908 +0000] - Checking policies
[2021-08-30T10:24:22.900Z] [INFO] [2021-08-30 10:24:22,709 +0000] - All dependencies conform with open source policies.
[2021-08-30T10:24:22.900Z] [INFO] [2021-08-30 10:24:22,710 +0000] - Check Policies Support Token: 281dd3f8802fc49ca8e7655c9004fa3bf1630319061632
[2021-08-30T10:24:23.161Z] [INFO] [2021-08-30 10:24:22,960 +0000] - Policies report generated successfully
[2021-08-30T10:24:23.161Z] [INFO] [2021-08-30 10:24:22,961 +0000] - 
[2021-08-30T10:24:23.161Z] ------------------------------------------------------------------------
[2021-08-30T10:24:23.161Z] -------------------- End: Check Policies -------------------------------
[2021-08-30T10:24:23.161Z] ------------------------------------------------------------------------
[2021-08-30T10:24:23.161Z] [INFO] [2021-08-30 10:24:22,961 +0000] - Sending Update
[2021-08-30T10:24:23.161Z] [INFO] [2021-08-30 10:24:22,962 +0000] - 
[2021-08-30T10:24:23.161Z] ------------------------------------------------------------------------
[2021-08-30T10:24:23.161Z] -------------------- Start: Update Inventory ---------------------------
[2021-08-30T10:24:23.161Z] ------------------------------------------------------------------------
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,126 +0000] - 
[2021-08-30T10:24:24.549Z] ------------------------------------------------------------------------
[2021-08-30T10:24:24.549Z] -------------------- End: Update Inventory -----------------------------
[2021-08-30T10:24:24.549Z] ------------------------------------------------------------------------
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,126 +0000] - Inventory update results for SAP SE
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,126 +0000] - No new projects found.
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,126 +0000] - Updated projects:
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,126 +0000] - # <projectName>
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,126 +0000] - Project name: <projectName>, URL: <project>
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,126 +0000] - Support Token: 0afdba2a801154f678296041e13304aa31630319063018
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,129 +0000] - Log files are found at: ./whitesource/Mon-Aug-30-2021-10.24.19
[2021-08-30T10:24:24.549Z] [INFO] [2021-08-30 10:24:24,135 +0000] - 
[2021-08-30T10:24:24.549Z] ------------------------------------------------------------------------------------------------------------------------------------------------------
[2021-08-30T10:24:24.549Z] ------------------------------------------------------------- WhiteSource Scan Summary: --------------------------------------------------------------
[2021-08-30T10:24:24.549Z] ------------------------------------------------------------------------------------------------------------------------------------------------------
[2021-08-30T10:24:24.549Z] ======================================================================================================================================================
[2021-08-30T10:24:24.549Z] Scan Origin: Local File System
[2021-08-30T10:24:24.549Z] ======================================================================================================================================================
[2021-08-30T10:24:24.549Z] Step                                              Completion Status               Elapsed                  Comments
[2021-08-30T10:24:24.549Z] ======================================================================================================================================================
[2021-08-30T10:24:24.549Z] Fetch Configuration                                  COMPLETED                  00:00:00.077               --------
[2021-08-30T10:24:24.549Z] Pre-Step And Resolve Dependencies                    COMPLETED                  00:00:00.018               0 dependencies
[2021-08-30T10:24:24.549Z] Scan Files Matching Includes Pattern                 COMPLETED                  00:00:00.067               0 source/binary files
[2021-08-30T10:24:24.549Z] Check Policies                                       COMPLETED                  00:00:02.053               --------
[2021-08-30T10:24:24.549Z] Update Inventory                                     COMPLETED                  00:00:01.164               1 updated projects
[2021-08-30T10:24:24.549Z] 
[2021-08-30T10:24:24.549Z] ======================================================================================================================================================
[2021-08-30T10:24:24.549Z] Elapsed running time:                                                           00:00:03.379
[2021-08-30T10:24:24.549Z] ======================================================================================================================================================
[2021-08-30T10:24:24.549Z] Process finished with exit code SUCCESS (0)`

**Comment by LenaKleyner** [comment]
Thanks @JulianHauber for sharing this information but I would like our support team to examine the logs from both scans. Could you kindly create a support case for this issue and include the logs as well?

Thanks,

Lena

**Comment by JulianHauber** [comment]
@LenaKleyner, I have create a support case for this issue. Thank you for your help.

Best regards,
Julian

**Comment by chengshifan** [comment]
Hi Team, 
I also find that there is something wrong with 21.8.1.
The error message is 

```
[2021-08-31T02:47:40.450Z] java.lang.NullPointerException: null
[2021-08-31T02:47:40.450Z] 	at org.whitesource.agent.dependency.resolver.go.GoDependencyResolver.getPackageManager(GoDependencyResolver.java:44)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.agent.dependency.resolver.DependencyResolutionService.resolveDependenciesOfResolver(DependencyResolutionService.java:428)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.agent.dependency.resolver.DependencyResolutionService.resolveDependencies(DependencyResolutionService.java:207)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.agent.FileSystemScanner.createProjects(FileSystemScanner.java:255)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.fs.scanOrigins.GeneralScanOrigin.getProjects(GeneralScanOrigin.java:189)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.fs.scanOrigins.GeneralScanOrigin.scan(GeneralScanOrigin.java:98)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.fs.scanOrigins.ScanOrigin.runOriginScan(ScanOrigin.java:36)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.fs.FileSystemAgent.createProjects(FileSystemAgent.java:165)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.fs.Main.scanProjects(Main.java:116)
[2021-08-31T02:47:40.450Z] 	at org.whitesource.fs.Main.main(Main.java:91)
```

But the 21.7.2 is OK.

**Comment by LenaKleyner** [comment]
Thanks @JulianHauber .

@chengshifan, you might be experiencing a different issue. Could you please create a support case and include all the relevant information (the Unified Agent execution command, its settings, and the output log) so that our support team will be able to examine it properly? 

Thanks,

Lena

**Comment by nabeelsaabna** [comment]
Hi @JulianHauber 
issue was fix a while ago, therefor closing the issue.
