### ISSUE TITLE
sendScanResults fails with NullPointerException in v22.4.1

### ISSUE THREAD

**Issue by LynAutumn** [whitesource/unified-agent-distribution#34]
Our pipeline worked fine with the previous versions, with the latest upgrade to v22.4.1 happening yesterday, all scan-pipelines fail with a NullPointerException. When checking the provided [jar](https://github.com/whitesource/unified-agent-distribution/releases/tag/v22.4.1) there's also an "internal error" when trying to open the file "WssServiceClientImpl". 
Will there be a fixed version or did this include a breaking change that must be adapted on our side? 

Stacktrace: 
```
[DEBUG] [2022-05-01 14:43:41,294 +0200[ - Failed to send request to WhiteSource server: Server error: java.lang.NullPointerException
org.whitesource.agent.client.WssServiceException: Server error: java.lang.NullPointerException
	at org.whitesource.agent.client.WssServiceClientImpl.extractResultData(WssServiceClientImpl.java:492)
	at org.whitesource.agent.client.WssServiceClientImpl.service(WssServiceClientImpl.java:339)
	at org.whitesource.agent.client.WssServiceClientImpl.checkPolicyCompliance(WssServiceClientImpl.java:209)
	at org.whitesource.agent.client.WhitesourceService.checkPolicyCompliance(WhitesourceService.java:623)
	at org.whitesource.request.ProjectsSender.checkPolicies(ProjectsSender.java:730)
	at org.whitesource.request.ProjectsSender.sendRequest(ProjectsSender.java:270)
	at org.whitesource.request.ProjectsSender.sendProjects(ProjectsSender.java:165)
	at org.whitesource.fs.Main.sendScanResults(Main.java:209)
	at org.whitesource.fs.Main.main(Main.java:95)
[INFO] [2022-05-01 14:43:41,296 +0200[ - Process finished with exit code SERVER_FAILURE (Failed to send request to WhiteSource server: Server error: java.lang.NullPointerException
```

**Comment by LenaKleyner** [comment]
Hi @LynAutumn ,

Could you please open a ticket in our [support portal](https://whitesourcesoftware.force.com/SupportPortal/s/login/) with all the relevant information (the Unified Agent execution command, its settings, and the output log)?

Thanks!

Lena
