### ISSUE TITLE
release 24.9.1 fails with  "org.whitesource.termination.SystemExit.fsaConfiguration" is null

### ISSUE THREAD

**Issue by Sven1410** [whitesource/unified-agent-distribution#59]
java -jar wss-unified-agent.jar -v

24.9.1
[ERROR] [2024-09-24 14:41:11,457 +0200] - Failed to run main: Cannot invoke "org.whitesource.config.FSAConfigurationManager.getRequest()" because "org.whitesource.termination.SystemExit.fsaConfiguration" is null
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.whitesource.config.FSAConfigurationManager.getRequest()" because "org.whitesource.termination.SystemExit.fsaConfiguration" is null
        at org.whitesource.termination.SystemExit.exit(SystemExit.java:34)
        at org.whitesource.fs.Main.main(Main.java:134)
        
        
this fails on multiple environments. (azure, local windows, ...)

it worked on 24.8.1:

java -jar .\wss-unified-agent24_8_1.jar -v
24.8.1

**Comment by Sven1410** [comment]
VM is :  https://github.com/SAP/SapMachine

**Comment by I069405** [comment]
Our project facing the same issue now

**Comment by LenaKleyner** [comment]
Thanks for raising this, a hot fix addressing this was released. 
Please use the latest UA version 24.9.1.1.
